/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EntryGrid: typeof import('./../components/biz/EntryGrid.vue')['default']
    EntryTile: typeof import('./../components/ui/EntryTile.vue')['default']
    IdentityBar: typeof import('./../components/ui/IdentityBar.vue')['default']
    InternalAdminBlock: typeof import('./../components/biz/InternalAdminBlock.vue')['default']
    LoadState: typeof import('./../components/ui/LoadState.vue')['default']
    MeHeader: typeof import('./../components/biz/MeHeader.vue')['default']
    MeRow: typeof import('./../components/biz/MeRow.vue')['default']
    MeSectionTitle: typeof import('./../components/biz/MeSectionTitle.vue')['default']
    PlaceholderPage: typeof import('./../components/ui/PlaceholderPage.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
