/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttachmentList: typeof import('./../components/lqg/AttachmentList.vue')['default']
    CryoBatchSheet: typeof import('./../components/lqg/CryoBatchSheet.vue')['default']
    CryoFlowForm: typeof import('./../components/lqg/CryoFlowForm.vue')['default']
    CryoLn2Form: typeof import('./../components/lqg/CryoLn2Form.vue')['default']
    DocGroupCard: typeof import('./../components/lqg/DocGroupCard.vue')['default']
    DocTabs: typeof import('./../components/lqg/DocTabs.vue')['default']
    DownloadBar: typeof import('./../components/lqg/DownloadBar.vue')['default']
    DownloadSheet: typeof import('./../components/lqg/DownloadSheet.vue')['default']
    EmbedCard: typeof import('./../components/lqg/EmbedCard.vue')['default']
    EmptyState: typeof import('./../components/lqg/EmptyState.vue')['default']
    EntryGrid: typeof import('./../components/biz/EntryGrid.vue')['default']
    EntryTile: typeof import('./../components/ui/EntryTile.vue')['default']
    ErrorState: typeof import('./../components/lqg/ErrorState.vue')['default']
    FieldRow: typeof import('./../components/lqg/FieldRow.vue')['default']
    IdentityBar: typeof import('./../components/ui/IdentityBar.vue')['default']
    InternalAdminBlock: typeof import('./../components/biz/InternalAdminBlock.vue')['default']
    LedgerTable: typeof import('./../components/lqg/LedgerTable.vue')['default']
    LegalArticle: typeof import('./../components/ui/LegalArticle.vue')['default']
    LineIcon: typeof import('./../components/ui/LineIcon.vue')['default']
    LoadingState: typeof import('./../components/lqg/LoadingState.vue')['default']
    LoadState: typeof import('./../components/ui/LoadState.vue')['default']
    MarkerRows: typeof import('./../components/lqg/MarkerRows.vue')['default']
    MeHeader: typeof import('./../components/biz/MeHeader.vue')['default']
    MeRow: typeof import('./../components/biz/MeRow.vue')['default']
    MeSectionTitle: typeof import('./../components/biz/MeSectionTitle.vue')['default']
    NoteBar: typeof import('./../components/lqg/NoteBar.vue')['default']
    OcrBar: typeof import('./../components/lqg/OcrBar.vue')['default']
    PageImageViewer: typeof import('./../components/lqg/PageImageViewer.vue')['default']
    PlaceholderPage: typeof import('./../components/ui/PlaceholderPage.vue')['default']
    QcAttachmentList: typeof import('./../components/lqg/QcAttachmentList.vue')['default']
    QcImageSlot: typeof import('./../components/lqg/QcImageSlot.vue')['default']
    ReasonSheet: typeof import('./../components/lqg/ReasonSheet.vue')['default']
    SampleCard: typeof import('./../components/lqg/SampleCard.vue')['default']
    SamplePicker: typeof import('./../components/lqg/SamplePicker.vue')['default']
    SamplePickerExt: typeof import('./../components/lqg/SamplePickerExt.vue')['default']
    SegButtons: typeof import('./../components/lqg/SegButtons.vue')['default']
    SourceUnitSheet: typeof import('./../components/lqg/SourceUnitSheet.vue')['default']
    StainButtons: typeof import('./../components/lqg/StainButtons.vue')['default']
    StatusChip: typeof import('./../components/lqg/StatusChip.vue')['default']
    ThumbStrip: typeof import('./../components/lqg/ThumbStrip.vue')['default']
    TodoCard: typeof import('./../components/biz/TodoCard.vue')['default']
    UnitGroupPicker: typeof import('./../components/biz/UnitGroupPicker.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
  }
}
