/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/admin/cryo" |
  "/pages/admin/embed" |
  "/pages/admin/organoid" |
  "/pages/admin/sample" |
  "/pages/cryo/form" |
  "/pages/docs/index" |
  "/pages/embed/form" |
  "/pages/history/index" |
  "/pages/legal/agreement" |
  "/pages/legal/privacy" |
  "/pages/login/index" |
  "/pages/me/index" |
  "/pages/me/unit-group" |
  "/pages/organoid/form" |
  "/pages/sample/detail-ext" |
  "/pages/sample/form";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/docs/index" | "/pages/me/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
